import {
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
	chmodSync,
	renameSync,
} from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const PAW_DIR = join(homedir(), ".paw");
const LEGACY_DIR = join(homedir(), ".clawme");
const CREDENTIALS_PATH = join(PAW_DIR, "credentials.json");
const CLAUDE_CREDENTIALS_PATH = join(homedir(), ".claude", ".credentials.json");

/** Migrate ~/.clawme → ~/.paw on first run after rename. */
function migrateFromClawMe(): void {
	if (existsSync(LEGACY_DIR) && !existsSync(PAW_DIR)) {
		try {
			renameSync(LEGACY_DIR, PAW_DIR);
		} catch {
			// If rename fails (cross-device), fall through — user will re-init
		}
	}
}

export interface StoredCredentials {
	provider?: "claude" | "ollama" | "openai" | "gemini";
	anthropic?: {
		method: "api_key" | "oauth";
		apiKey?: string;
		accessToken?: string;
		refreshToken?: string;
		expiresAt?: string;
	};
	ollama?: {
		baseUrl: string;
		model: string;
	};
	openai?: {
		apiKey: string;
		model?: string;
		baseUrl?: string;
	};
	gemini?: {
		apiKey: string;
		model?: string;
	};
	slack?: {
		botToken: string;
		appToken: string;
		signingSecret: string;
	};
}

export interface AnthropicCredentials {
	token: string;
	method: "api_key" | "oauth";
}

function ensureDir(): void {
	migrateFromClawMe();
	if (!existsSync(PAW_DIR)) {
		mkdirSync(PAW_DIR, { recursive: true, mode: 0o700 });
	}
}

export function loadCredentials(): StoredCredentials {
	ensureDir();
	if (!existsSync(CREDENTIALS_PATH)) return {};

	try {
		return JSON.parse(readFileSync(CREDENTIALS_PATH, "utf-8"));
	} catch {
		return {};
	}
}

export function saveCredentials(creds: StoredCredentials): void {
	ensureDir();
	writeFileSync(CREDENTIALS_PATH, JSON.stringify(creds, null, 2) + "\n", {
		mode: 0o600,
	});
	chmodSync(CREDENTIALS_PATH, 0o600);
}

export function clearCredentials(service?: "anthropic" | "slack"): void {
	if (!service) {
		if (existsSync(CREDENTIALS_PATH)) {
			writeFileSync(CREDENTIALS_PATH, "{}\n", { mode: 0o600 });
		}
		return;
	}

	const creds = loadCredentials();
	delete creds[service];
	saveCredentials(creds);
}

/**
 * Read the OAuth token generated by `claude setup-token`.
 * Stored at ~/.claude/.credentials.json by the Claude CLI.
 */
export function readClaudeToken():
	| { accessToken: string; refreshToken?: string; expiresAt?: number }
	| undefined {
	if (!existsSync(CLAUDE_CREDENTIALS_PATH)) return undefined;

	try {
		const data = JSON.parse(readFileSync(CLAUDE_CREDENTIALS_PATH, "utf-8"));
		const oauth = data.claudeAiOauth;
		if (oauth?.accessToken) {
			return {
				accessToken: oauth.accessToken,
				refreshToken: oauth.refreshToken,
				expiresAt: oauth.expiresAt,
			};
		}
	} catch {}

	return undefined;
}

/**
 * Resolve Anthropic credentials with priority:
 * 1. Stored OAuth token from `paw auth login` (user's Max/Pro membership)
 *    — but only if the token is still valid
 * 2. Claude CLI OAuth token from `claude setup-token`
 * 3. Stored API key in ~/.paw/credentials.json
 * 4. ANTHROPIC_API_KEY env var (fallback for CI/Docker)
 *
 * OAuth takes priority because if the user explicitly logged in with
 * their membership, a stale API key in .env shouldn't override that.
 */
export function getAnthropicCredentials(): AnthropicCredentials | undefined {
	const creds = loadCredentials();

	// 1. Stored OAuth token (user explicitly chose membership via `paw auth login`)
	if (creds.anthropic?.method === "oauth" && creds.anthropic.accessToken) {
		// Skip expired tokens
		if (creds.anthropic.expiresAt) {
			const expiresAt = new Date(creds.anthropic.expiresAt).getTime();
			if (expiresAt > Date.now()) {
				return { token: creds.anthropic.accessToken, method: "oauth" };
			}
			// Token expired — fall through to next option
		} else {
			return { token: creds.anthropic.accessToken, method: "oauth" };
		}
	}

	// 2. Claude CLI OAuth token (from `claude setup-token`)
	const claudeToken = readClaudeToken();
	if (claudeToken) {
		// Check expiry if available
		if (!claudeToken.expiresAt || claudeToken.expiresAt * 1000 > Date.now()) {
			return { token: claudeToken.accessToken, method: "oauth" };
		}
	}

	// 3. Stored API key
	if (creds.anthropic?.method === "api_key" && creds.anthropic.apiKey) {
		return { token: creds.anthropic.apiKey, method: "api_key" };
	}

	// 4. Env var fallback (CI/Docker)
	if (process.env.ANTHROPIC_API_KEY) {
		return { token: process.env.ANTHROPIC_API_KEY, method: "api_key" };
	}

	return undefined;
}

/** @deprecated Use getAnthropicCredentials() instead */
export function getAnthropicKey(): string | undefined {
	return getAnthropicCredentials()?.token;
}

export function getSlackCredentials():
	| { botToken: string; appToken: string; signingSecret: string }
	| undefined {
	const creds = loadCredentials();
	if (process.env.SLACK_BOT_TOKEN && process.env.SLACK_APP_TOKEN) {
		return {
			botToken: process.env.SLACK_BOT_TOKEN,
			appToken: process.env.SLACK_APP_TOKEN,
			signingSecret: process.env.SLACK_SIGNING_SECRET ?? "",
		};
	}
	if (creds.slack?.botToken && creds.slack?.appToken) {
		return creds.slack;
	}
	return undefined;
}

export function getStoredProvider(): "claude" | "ollama" | "openai" | "gemini" {
	const env = process.env.PAW_PROVIDER;
	if (
		env === "ollama" ||
		env === "claude" ||
		env === "openai" ||
		env === "gemini"
	)
		return env;
	const creds = loadCredentials();
	return creds.provider ?? "claude";
}

export function getOpenAICredentials():
	| { apiKey: string; model?: string; baseUrl?: string }
	| undefined {
	if (process.env.OPENAI_API_KEY) {
		return {
			apiKey: process.env.OPENAI_API_KEY,
			model: process.env.PAW_OPENAI_MODEL,
			baseUrl: process.env.PAW_OPENAI_BASE_URL,
		};
	}
	const creds = loadCredentials();
	if (creds.openai?.apiKey) return creds.openai;
	return undefined;
}

export function getGeminiCredentials():
	| { apiKey: string; model?: string }
	| undefined {
	if (process.env.GEMINI_API_KEY) {
		return {
			apiKey: process.env.GEMINI_API_KEY,
			model: process.env.PAW_GEMINI_MODEL,
		};
	}
	const creds = loadCredentials();
	if (creds.gemini?.apiKey) return creds.gemini;
	return undefined;
}

export function getOllamaConfig():
	| { baseUrl: string; model: string }
	| undefined {
	const creds = loadCredentials();
	if (creds.ollama?.baseUrl) return creds.ollama;
	if (process.env.PAW_OLLAMA_BASE_URL) {
		return {
			baseUrl: process.env.PAW_OLLAMA_BASE_URL,
			model: process.env.PAW_OLLAMA_MODEL ?? "llama3.1",
		};
	}
	return undefined;
}

export function getCredentialsPath(): string {
	return CREDENTIALS_PATH;
}

export function getClaudeCredentialsPath(): string {
	return CLAUDE_CREDENTIALS_PATH;
}
